// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// // ...

// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQoo3AIendANtsD-_kA_2Js2hWeWenPUw',
    appId: '1:1011402038484:web:3b11f086a3b56ebd616f41',
    messagingSenderId: '1011402038484',
    projectId: 'flutter-weather-app-e936d',
    authDomain: 'flutter-weather-app-e936d.firebaseapp.com',
    storageBucket: 'flutter-weather-app-e936d.appspot.com',
    measurementId: 'G-5CMQCW8DY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctAVi0AThlM53Q-tAMpABGa39XXC2f7Y',
    appId: '1:1011402038484:android:9d6b13a6fc0848f8616f41',
    messagingSenderId: '1011402038484',
    projectId: 'flutter-weather-app-e936d',
    storageBucket: 'flutter-weather-app-e936d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI_l-7KS-zcDl_8T9Ge9DOlBZXwZZS8tY',
    appId: '1:1011402038484:ios:3e96e857c31a564d616f41',
    messagingSenderId: '1011402038484',
    projectId: 'flutter-weather-app-e936d',
    storageBucket: 'flutter-weather-app-e936d.appspot.com',
    iosClientId: '1011402038484-sf2js9a20ok98gb5tll2b4mln9efgtvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherForecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI_l-7KS-zcDl_8T9Ge9DOlBZXwZZS8tY',
    appId: '1:1011402038484:ios:3e96e857c31a564d616f41',
    messagingSenderId: '1011402038484',
    projectId: 'flutter-weather-app-e936d',
    storageBucket: 'flutter-weather-app-e936d.appspot.com',
    iosClientId: '1011402038484-sf2js9a20ok98gb5tll2b4mln9efgtvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherForecast',
  );
}
